{
 "title": "SQL Task Queue",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "resolution", "label": "Resolution (sec)", "query": "60,300,3600" }
  ]
 },
 "panels": [
  {
   "title": "Tasks created",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH topics AS (select distinct topic from queue_tasks)\nSELECT\n  to_timestamp(floor(date_part('epoch', dd)/$resolution)*$resolution) as time,\n  topics.topic as metric,\n  (SELECT COUNT(*) FROM queue_tasks where topic = topics.topic AND to_timestamp(floor(date_part('epoch', added_at)/$resolution)*$resolution) = to_timestamp(floor(date_part('epoch', dd)/$resolution)*$resolution))\nFROM\ngenerate_series(to_timestamp($__unixEpochFrom()), to_timestamp($__unixEpochTo()), $resolution*interval '1 sec') dd\nCROSS JOIN\ntopics\nORDER BY\n  dd\n"
    }
   ]
  },
  {
   "title": "Tasks canceled",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH topics AS (select distinct topic from queue_tasks)\nSELECT\n  to_timestamp(floor(date_part('epoch', dd)/$resolution)*$resolution) as time,\n  topics.topic as metric,\n  (SELECT COUNT(*) FROM queue_tasks where topic = topics.topic AND to_timestamp(floor(date_part('epoch', canceled_at)/$resolution)*$resolution) = to_timestamp(floor(date_part('epoch', dd)/$resolution)*$resolution))\nFROM\ngenerate_series(to_timestamp($__unixEpochFrom()), to_timestamp($__unixEpochTo()), $resolution*interval '1 sec') dd\nCROSS JOIN\ntopics\nORDER BY\n  dd\n"
    }
   ]
  },
  {
   "title": "Tasks started",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH topics AS (select distinct topic from queue_tasks)\nSELECT\n  to_timestamp(floor(date_part('epoch', dd)/$resolution)*$resolution) as time,\n  topics.topic as metric,\n  (SELECT COUNT(*) FROM queue_tasks where topic = topics.topic AND to_timestamp(floor(date_part('epoch', started_at)/$resolution)*$resolution) = to_timestamp(floor(date_part('epoch', dd)/$resolution)*$resolution))\nFROM\ngenerate_series(to_timestamp($__unixEpochFrom()), to_timestamp($__unixEpochTo()), $resolution*interval '1 sec') dd\nCROSS JOIN\ntopics\nORDER BY\n  dd\n"
    }
   ]
  },
  {
   "title": "Tasks created but not started",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('min', added_at) as time,\n  topic as metric,\n  count(*)\nFROM\n  queue_tasks\nWHERE\n  $__timeFilter(added_at)\n  AND started_at is null\nGROUP BY topic, date_trunc('min', added_at)\nORDER BY date_trunc('min', added_at)"
    }
   ]
  },
  {
   "title": "Tasks committed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH topics AS (select distinct topic from queue_tasks)\nSELECT\n  to_timestamp(floor(date_part('epoch', dd)/$resolution)*$resolution) as time,\n  topics.topic as metric,\n  (SELECT COUNT(*) FROM queue_tasks where topic = topics.topic AND to_timestamp(floor(date_part('epoch', committed_at)/$resolution)*$resolution) = to_timestamp(floor(date_part('epoch', dd)/$resolution)*$resolution))\nFROM\ngenerate_series(to_timestamp($__unixEpochFrom()), to_timestamp($__unixEpochTo()), $resolution*interval '1 sec') dd\nCROSS JOIN\ntopics\nORDER BY\n  dd\n"
    }
   ]
  },
  {
   "title": "Tasks not started",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "select\n  topic,\n  count(*)\nfrom queue_tasks where committed_at is null and canceled_at is null and started_at is null group by topic"
    }
   ]
  },
  {
   "title": "Average task duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('min', started_at) as time,\n  topic as metric,\n  avg(extract(epoch from committed_at - started_at))\nFROM\n  queue_tasks\nWHERE\n  $__timeFilter(started_at)\nGROUP BY topic, date_trunc('min', started_at)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Tasks in progress",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "rawSql": "select\n  id,\n  topic,\n  consumer_id\nfrom queue_tasks\nwhere\n  committed_at is null\n  and canceled_at is null\n  and heartbeat_deadline > now()"
    }
   ]
  },
  {
   "title": "Average task wait time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('min', added_at) as time,\n  topic as metric,\n  avg(extract(epoch from started_at - added_at))\nFROM\n  queue_tasks\nWHERE\n  $__timeFilter(added_at)\nGROUP BY topic, date_trunc('min', added_at)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Recent tasks",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  id, topic, retries_left, added_at, started_at, committed_at,\n  canceled_at\nFROM queue_tasks WHERE $__timeFilter(added_at) OR $__timeFilter(started_at) OR $__timeFilter(committed_at) ORDER BY id DESC LIMIT 100;",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}